title: Bong-Netflix
desctiption: Here lies the titles available in Netflix Bangladesh
url: "" 
permalink: '/:title'
markdown: kramdown
baseurl: "/BongNetflix" # the subpath of your site, e.g. /blog

sass:
    style: compressed

compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

highlight: rouge

include: [_pages]
version: 0.1

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 50
paginate_path: /page:num/
